### ISSUE TITLE
npm无法下载

### ISSUE THREAD

**Issue by greenhandzdl** [xtuJSer/CoCoMusic#150]
[greenhandzdl@localhost CoCoMusic]$ npm run dev

> cocomusic@2.0.7 dev /home/greenhandzdl/Desktop/CoCoMusic
> node .electron-vue/dev-runner.js

         ___                      __                                                                
   __   /\_ \       __     ___   /\ \__    _ __    ___     ___              __  __  __  __     __   
 / ,.`\ \//\ \    / ,.`\  /'___\ \ \ ,_\  /\` __\ / __`\ /' _ `\   _______ /\ \/\ \/\ \/\ \  / ,.`\ 
/\  __/   \_\ \_ /\  __/ /\ \__/  \ \ \/  \ \ \/ /\ \_\ \/\ \/\ \ /\______\\ \ \/ |\ \ \_\ \/\  __/ 
\ \____\  /\____\\ \____\\ \____\  \ \ \_  \ \_\ \ \____/\ \_\ \_\\/______/ \ \___/ \ \____/\ \____\
 \/____/  \/____/ \/____/ \/____/   \ \__\  \/_/  \/___/  \/_/\/_/           \/__/   \/___/  \/____/
                                     \/__/                                                          
  getting ready...

┏ Main Process ---------------

  compiling...

┗ ----------------------------

ℹ ｢wds｣: Project is running at http://localhost:9080/
ℹ ｢wds｣: webpack output is served from undefined
ℹ ｢wds｣: Content not from webpack is served from /home/greenhandzdl/Desktop/CoCoMusic/
┏ Renderer Process -----------

  Hash: c3ce6b2a21d057383570
  Version: webpack 4.44.2
  Time: 12297ms
  Built at: 2021-01-02 10:55:30 PM
        Asset       Size    Chunks             Chunk Names
   index.html  418 bytes            [emitted]  
  renderer.js   5.32 MiB  renderer  [emitted]  renderer
  Entrypoint renderer = renderer.js
  [1] multi ./node_modules/_webpack-dev-server@3.11.1@webpack-dev-server/client?http://localhost ./.electron-vue/dev-client ./src/renderer/main.js 52 bytes {renderer} [built]
  [./.electron-vue/dev-client.js] 731 bytes {renderer} [built]
  [./node_modules/_spectre.css@0.5.9@spectre.css/dist/spectre-exp.css] 1 KiB {renderer} [built]
  [./node_modules/_spectre.css@0.5.9@spectre.css/dist/spectre-icons.css] 1.01 KiB {renderer} [built]
  [./node_modules/_spectre.css@0.5.9@spectre.css/dist/spectre.css] 1010 bytes {renderer} [built]
  [./node_modules/_strip-ansi@3.0.1@strip-ansi/index.js] 161 bytes {renderer} [built]
  [./node_modules/_vue@2.6.12@vue/dist/vue.esm.js] 319 KiB {renderer} [built]
  [./node_modules/_webpack-dev-server@3.11.1@webpack-dev-server/client/index.js?http://localhost] ./node_modules/_webpack-dev-server@3.11.1@webpack-dev-server/client?http://localhost 4.29 KiB {renderer} [built]
  [./node_modules/_webpack-dev-server@3.11.1@webpack-dev-server/client/overlay.js] 3.51 KiB {renderer} [built]
  [./node_modules/_webpack-dev-server@3.11.1@webpack-dev-server/client/socket.js] 1.53 KiB {renderer} [built]
  [./node_modules/_webpack-dev-server@3.11.1@webpack-dev-server/client/utils/createSocketUrl.js] 2.91 KiB {renderer} [built]
  [./node_modules/_webpack-dev-server@3.11.1@webpack-dev-server/client/utils/log.js] 964 bytes {renderer} [built]
  [./node_modules/_webpack-dev-server@3.11.1@webpack-dev-server/client/utils/reloadApp.js] 1.59 KiB {renderer} [built]
  [./node_modules/_webpack-dev-server@3.11.1@webpack-dev-server/client/utils/sendMessage.js] 402 bytes {renderer} [built]
  [./src/renderer/main.js] 591 bytes {renderer} [built]
      + 463 hidden modules
  Child html-webpack-plugin for "index.html":
           Asset      Size  Chunks  Chunk Names
      index.html  1.37 MiB       0  
      Entrypoint undefined = index.html
      [./node_modules/_html-webpack-plugin@3.2.0@html-webpack-plugin/lib/loader.js!./src/index.ejs] 1.16 KiB {0} [built]
      [./node_modules/_lodash@4.17.20@lodash/lodash.js] 530 KiB {0} [built]
      [./node_modules/_webpack@4.44.2@webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]

┗ ----------------------------

┏ Main Process ---------------

  Hash: dc27cc65a835c46bfe0d
  Version: webpack 4.44.2
  Time: 13429ms
  Built at: 2021-01-02 10:55:31 PM
    Asset     Size  Chunks             Chunk Names
  main.js  659 KiB    main  [emitted]  main
  Entrypoint main = main.js
  [0] multi ./src/main/index.dev.js ./src/main/index.js 40 bytes {main} [built]
  [./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/json/stringify.js] 95 bytes {main} [built]
  [./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/object/assign.js] 94 bytes {main} [built]
  [./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/object/keys.js] 92 bytes {main} [built]
  [./node_modules/_babel-runtime@6.26.0@babel-runtime/helpers/typeof.js] 1.04 KiB {main} [built]
  [./node_modules/_electron-debug@1.5.0@electron-debug sync recursive] ./node_modules/_electron-debug@1.5.0@electron-debug sync 160 bytes {main} [built]
  [./node_modules/_electron-debug@1.5.0@electron-debug/index.js] 2.46 KiB {main} [built]
  [./node_modules/_electron-devtools-installer@2.2.4@electron-devtools-installer/dist/index.js] 5.02 KiB {main} [built]

Hash: e0534961bf644f4e2096
Version: webpack 4.44.2
Time: 33549ms
Built at: 2021-01-02 10:57:17 PM
  Asset      Size  Chunks             Chunk Names
main.js  68.7 KiB       0  [emitted]  main
Entrypoint main = main.js
  [0] external "electron" 42 bytes {0} [built]
 [22] ./src/main/localStorage.js 2.47 KiB {0} [built]
 [39] ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/object/keys.js 92 bytes {0} [built]
 [68] external "path" 42 bytes {0} [built]
 [80] ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/object/assign.js 94 bytes {0} [built]
 [81] ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/json/stringify.js 95 bytes {0} [built]
 [82] ./node_modules/_lodash@4.17.20@lodash/fp/placeholder.js 105 bytes {0} [built]
[134] ./node_modules/_lodash@4.17.20@lodash/fp/flow.js 153 bytes {0} [built]
[135] ./node_modules/_babel-runtime@6.26.0@babel-runtime/helpers/typeof.js 1.04 KiB {0} [built]
[136] ./node_modules/_lodash@4.17.20@lodash/fp/convert.js 657 bytes {0} [built]
[255] ./node_modules/_lodash@4.17.20@lodash/flow.js 666 bytes {0} [built]
[266] external "fs" 42 bytes {0} [built]
[267] external "os" 42 bytes {0} [built]
[268] ./src/main/hotKey.js 4.23 KiB {0} [built]
[295] ./src/main/index.js + 1 modules 4.09 KiB {0} [built]
      | ./src/main/index.js 2.93 KiB [built]
      | ./src/main/tray.js 1.15 KiB [built]
    + 281 hidden modules

Hash: 8b1cc16b86f09fff4817
Version: webpack 4.44.2
Time: 33562ms
Built at: 2021-01-02 10:57:17 PM
                           Asset       Size  Chunks             Chunk Names
                      index.html  314 bytes          [emitted]  
                     renderer.js    448 KiB       0  [emitted]  renderer
        static/css/darktheme.css    1.1 KiB          [emitted]  
static/font/Orbitron-Regular.ttf   38.4 KiB          [emitted]  
          static/img/256x256.png   32.4 KiB          [emitted]  
            static/img/32x32.png   2.56 KiB          [emitted]  
         static/img/Favorite.svg   1.67 KiB          [emitted]  
         static/img/PlayList.svg   3.13 KiB          [emitted]  
           static/img/Search.svg   2.16 KiB          [emitted]  
          static/img/Setting.svg   5.74 KiB          [emitted]  
           static/img/Singer.svg   1.82 KiB          [emitted]  
       static/img/SingerList.svg   3.15 KiB          [emitted]  
            static/img/music.svg   8.65 KiB          [emitted]  
             static/loading.html  424 bytes          [emitted]  
Entrypoint renderer = renderer.js
  [7] ./node_modules/_vue-style-loader@4.1.2@vue-style-loader/lib/addStylesClient.js + 1 modules 6.71 KiB {0} [built]
      | ./node_modules/_vue-style-loader@4.1.2@vue-style-loader/lib/addStylesClient.js 6.09 KiB [built]
      | ./node_modules/_vue-style-loader@4.1.2@vue-style-loader/lib/listToStyles.js 637 bytes [built]
  [8] ./src/renderer/store/index.js 202 bytes {0} [built]
  [9] external "vuex" 42 bytes {0} [built]
 [10] external "axios" 42 bytes {0} [built]
 [11] ./node_modules/_babel-runtime@6.26.0@babel-runtime/helpers/extends.js 544 bytes {0} [built]
 [16] ./node_modules/_vue@2.6.12@vue/dist/vue.esm.js 319 KiB {0} [built]
 [17] ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/json/stringify.js 95 bytes {0} [built]
 [32] ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/object/keys.js 92 bytes {0} [built]
 [70] ./src/renderer/store/modules/index.js 238 bytes {0} [built]
 [71] external "vue-router" 42 bytes {0} [built]
[281] ./node_modules/_spectre.css@0.5.9@spectre.css/dist/spectre.css 473 bytes {0} [built]
[283] ./node_modules/_spectre.css@0.5.9@spectre.css/dist/spectre-icons.css 479 bytes {0} [built]
[285] ./node_modules/_spectre.css@0.5.9@spectre.css/dist/spectre-exp.css 477 bytes {0} [built]
[287] external "vue-electron" 42 bytes {0} [built]
[288] ./src/renderer/main.js + 153 modules 147 KiB {0} [built]
      | ./src/renderer/main.js 591 bytes [built]
      | ./src/renderer/App.vue 529 bytes [built]
      | ./src/renderer/router/index.js 2.61 KiB [built]
      | ./src/renderer/common.js 365 bytes [built]
      | ./src/renderer/App.vue?vue&type=template&id=f1a9540a& 239 bytes [built]
      | ./node_modules/_vue-loader@15.9.6@vue-loader/lib/runtime/componentNormalizer.js 2.71 KiB [built]
      | ./src/renderer/App.vue?vue&type=script&lang=js& 422 bytes [built]
      | ./src/renderer/components/SingerList.vue 602 bytes [built]
      | ./src/renderer/components/Singer.vue 586 bytes [built]
      | ./src/renderer/components/SingerMusicList.vue 522 bytes [built]
      | ./src/renderer/components/SingerMvList.vue 513 bytes [built]
      | ./src/renderer/components/SingerAlbumList.vue 504 bytes [built]
      | ./src/renderer/components/MvPlayer.vue 594 bytes [built]
      | ./src/renderer/components/Search.vue 586 bytes [built]
      | ./src/renderer/components/Lyric.vue 582 bytes [built]
      |     + 139 hidden modules
    + 275 hidden modules
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  535 KiB       0  
    Entrypoint undefined = index.html
    [0] ./node_modules/_html-webpack-plugin@3.2.0@html-webpack-plugin/lib/loader.js!./src/index.ejs 1.16 KiB {0} [built]
    [1] ./node_modules/_lodash@4.17.20@lodash/lodash.js 530 KiB {0} [built]
    [2] (webpack)/buildin/module.js 497 bytes {0} [built]

 OKAY  take it away `electron-builder`

  • electron-builder version=20.44.4
  • loaded configuration file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config file=build/builder-effective-config.yaml
Error: Unresolved node modules: vue
    at /home/greenhandzdl/Desktop/CoCoMusic/node_modules/_app-builder-lib@20.44.4@app-builder-lib/src/util/packageDependencies.ts:112:21                                                                                                                                  
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/generators.js:97:49)                                                                                                                         
    at Promise._settlePromise (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:609:26)                                                                                                                                   
    at Promise._settlePromise0 (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:649:10)                                                                                                                                  
    at Promise._settlePromises (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:729:18)                                                                                                                                  
    at Promise._fulfill (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:466:57)                                                                                                                                 
    at Promise._settlePromiseFromHandler (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:559:17)                                                                                                                        
    at Promise._settlePromise (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:604:18)                                                                                                                                   
    at Promise._settlePromise0 (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:649:10)                                                                                                                                  
    at Promise._settlePromises (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:725:18)                                                                                                                                  
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@

Hash: e0534961bf644f4e2096
Version: webpack 4.44.2
Time: 24994ms
Built at: 2021-01-02 10:59:06 PM
  Asset      Size  Chunks             Chunk Names
main.js  68.7 KiB       0  [emitted]  main
Entrypoint main = main.js
  [0] external "electron" 42 bytes {0} [built]
 [22] ./src/main/localStorage.js 2.47 KiB {0} [built]
 [39] ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/object/keys.js 92 bytes {0} [built]
 [68] external "path" 42 bytes {0} [built]
 [80] ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/object/assign.js 94 bytes {0} [built]
 [81] ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/json/stringify.js 95 bytes {0} [built]
 [82] ./node_modules/_lodash@4.17.20@lodash/fp/placeholder.js 105 bytes {0} [built]
[134] ./node_modules/_lodash@4.17.20@lodash/fp/flow.js 153 bytes {0} [built]
[135] ./node_modules/_babel-runtime@6.26.0@babel-runtime/helpers/typeof.js 1.04 KiB {0} [built]
[136] ./node_modules/_lodash@4.17.20@lodash/fp/convert.js 657 bytes {0} [built]
[255] ./node_modules/_lodash@4.17.20@lodash/flow.js 666 bytes {0} [built]
[266] external "fs" 42 bytes {0} [built]
[267] external "os" 42 bytes {0} [built]
[268] ./src/main/hotKey.js 4.23 KiB {0} [built]
[295] ./src/main/index.js + 1 modules 4.09 KiB {0} [built]
      | ./src/main/index.js 2.93 KiB [built]
      | ./src/main/tray.js 1.15 KiB [built]
    + 281 hidden modules

Hash: 8b1cc16b86f09fff4817
Version: webpack 4.44.2
Time: 25191ms
Built at: 2021-01-02 10:59:07 PM
                           Asset       Size  Chunks             Chunk Names
                      index.html  314 bytes          [emitted]  
                     renderer.js    448 KiB       0  [emitted]  renderer
        static/css/darktheme.css    1.1 KiB          [emitted]  
static/font/Orbitron-Regular.ttf   38.4 KiB          [emitted]  
          static/img/256x256.png   32.4 KiB          [emitted]  
            static/img/32x32.png   2.56 KiB          [emitted]  
         static/img/Favorite.svg   1.67 KiB          [emitted]  
         static/img/PlayList.svg   3.13 KiB          [emitted]  
           static/img/Search.svg   2.16 KiB          [emitted]  
          static/img/Setting.svg   5.74 KiB          [emitted]  
           static/img/Singer.svg   1.82 KiB          [emitted]  
       static/img/SingerList.svg   3.15 KiB          [emitted]  
            static/img/music.svg   8.65 KiB          [emitted]  
             static/loading.html  424 bytes          [emitted]  
Entrypoint renderer = renderer.js
  [7] ./node_modules/_vue-style-loader@4.1.2@vue-style-loader/lib/addStylesClient.js + 1 modules 6.71 KiB {0} [built]
      | ./node_modules/_vue-style-loader@4.1.2@vue-style-loader/lib/addStylesClient.js 6.09 KiB [built]
      | ./node_modules/_vue-style-loader@4.1.2@vue-style-loader/lib/listToStyles.js 637 bytes [built]
  [8] ./src/renderer/store/index.js 202 bytes {0} [built]
  [9] external "vuex" 42 bytes {0} [built]
 [10] external "axios" 42 bytes {0} [built]
 [11] ./node_modules/_babel-runtime@6.26.0@babel-runtime/helpers/extends.js 544 bytes {0} [built]
 [16] ./node_modules/_vue@2.6.12@vue/dist/vue.esm.js 319 KiB {0} [built]
 [17] ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/json/stringify.js 95 bytes {0} [built]
 [32] ./node_modules/_babel-runtime@6.26.0@babel-runtime/core-js/object/keys.js 92 bytes {0} [built]
 [70] ./src/renderer/store/modules/index.js 238 bytes {0} [built]
 [71] external "vue-router" 42 bytes {0} [built]
[281] ./node_modules/_spectre.css@0.5.9@spectre.css/dist/spectre.css 473 bytes {0} [built]
[283] ./node_modules/_spectre.css@0.5.9@spectre.css/dist/spectre-icons.css 479 bytes {0} [built]
[285] ./node_modules/_spectre.css@0.5.9@spectre.css/dist/spectre-exp.css 477 bytes {0} [built]
[287] external "vue-electron" 42 bytes {0} [built]
[288] ./src/renderer/main.js + 153 modules 147 KiB {0} [built]
      | ./src/renderer/main.js 591 bytes [built]
      | ./src/renderer/App.vue 529 bytes [built]
      | ./src/renderer/router/index.js 2.61 KiB [built]
      | ./src/renderer/common.js 365 bytes [built]
      | ./src/renderer/App.vue?vue&type=template&id=f1a9540a& 239 bytes [built]
      | ./node_modules/_vue-loader@15.9.6@vue-loader/lib/runtime/componentNormalizer.js 2.71 KiB [built]
      | ./src/renderer/App.vue?vue&type=script&lang=js& 422 bytes [built]
      | ./src/renderer/components/SingerList.vue 602 bytes [built]
      | ./src/renderer/components/Singer.vue 586 bytes [built]
      | ./src/renderer/components/SingerMusicList.vue 522 bytes [built]
      | ./src/renderer/components/SingerMvList.vue 513 bytes [built]
      | ./src/renderer/components/SingerAlbumList.vue 504 bytes [built]
      | ./src/renderer/components/MvPlayer.vue 594 bytes [built]
      | ./src/renderer/components/Search.vue 586 bytes [built]
      | ./src/renderer/components/Lyric.vue 582 bytes [built]
      |     + 139 hidden modules
    + 275 hidden modules
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  535 KiB       0  
    Entrypoint undefined = index.html
    [0] ./node_modules/_html-webpack-plugin@3.2.0@html-webpack-plugin/lib/loader.js!./src/index.ejs 1.16 KiB {0} [built]
    [1] ./node_modules/_lodash@4.17.20@lodash/lodash.js 530 KiB {0} [built]
    [2] (webpack)/buildin/module.js 497 bytes {0} [built]

 OKAY  take it away `electron-builder`

  • electron-builder version=20.44.4
  • loaded configuration file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config file=build/builder-effective-config.yaml
Error: Unresolved node modules: vue
    at /home/greenhandzdl/Desktop/CoCoMusic/node_modules/_app-builder-lib@20.44.4@app-builder-lib/src/util/packageDependencies.ts:112:21
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/promise.js:725:18)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/debuggability.js:482:19)
    at new PromiseSpawn (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/generators.js:43:17)
    at /home/greenhandzdl/Desktop/CoCoMusic/node_modules/_bluebird@3.7.2@bluebird/js/release/generators.js:197:21
    at Packager.build (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_app-builder-lib@20.44.4@app-builder-lib/src/packager.ts:288:14)
    at build (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_app-builder-lib@20.44.4@app-builder-lib/src/index.ts:59:28)
    at build (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_electron-builder@20.44.4@electron-builder/src/builder.ts:228:10)
    at then (/home/greenhandzdl/Desktop/CoCoMusic/node_modules/_electron-builder@20.44.4@electron-builder/src/cli/cli.ts:49:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cocomusic@2.0.7 build:linux: `node .electron-vue/build.js && electron-builder -l tar.xz deb AppImage pacman`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cocomusic@2.0.7 build:linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-02T14_59_13_982Z-debug.log

**Comment by greenhandzdl** [comment]
[root@localhost CoCoMusic]# cat /root/.npm/_logs/2021-01-02T14_59_13_982Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm',
1 verbose cli   '--userconfig=/root/.cnpmrc',
1 verbose cli   '--disturl=https://npm.taobao.org/mirrors/node',
1 verbose cli   '--registry=https://r.npm.taobao.org',
1 verbose cli   'run',
1 verbose cli   'build:linux' ]
2 info using npm@6.14.10
3 info using node@v10.22.1
4 verbose run-script [ 'prebuild:linux', 'build:linux', 'postbuild:linux' ]
5 info lifecycle cocomusic@2.0.7~prebuild:linux: cocomusic@2.0.7
6 info lifecycle cocomusic@2.0.7~build:linux: cocomusic@2.0.7
7 verbose lifecycle cocomusic@2.0.7~build:linux: unsafe-perm in lifecycle true
8 verbose lifecycle cocomusic@2.0.7~build:linux: PATH: /usr/local/lib/node_modules/cnpm/node_modules/_npm@6.14.10@npm/node_modules/npm-lifecycle/node-gyp-bin:/home/greenhandzdl/Desktop/CoCoMusic/node_modules/.bin:/root/.local/bin:/root/bin:/home/greenhandzdl/.local/bin:/home/greenhandzdl/bin:/home/greenhandzdl/.local/bin:/home/greenhandzdl/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin
9 verbose lifecycle cocomusic@2.0.7~build:linux: CWD: /home/greenhandzdl/Desktop/CoCoMusic
10 silly lifecycle cocomusic@2.0.7~build:linux: Args: [ '-c',
10 silly lifecycle   'node .electron-vue/build.js && electron-builder -l tar.xz deb AppImage pacman' ]
11 silly lifecycle cocomusic@2.0.7~build:linux: Returned: code: 1  signal: null
12 info lifecycle cocomusic@2.0.7~build:linux: Failed to exec build:linux script
13 verbose stack Error: cocomusic@2.0.7 build:linux: `node .electron-vue/build.js && electron-builder -l tar.xz deb AppImage pacman`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/_npm@6.14.10@npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/_npm@6.14.10@npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid cocomusic@2.0.7
15 verbose cwd /home/greenhandzdl/Desktop/CoCoMusic
16 verbose Linux 4.18.0-259.el8.x86_64
17 verbose argv "/usr/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/root/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://r.npm.taobao.org" "run" "build:linux"
18 verbose node v10.22.1
19 verbose npm  v6.14.10
20 error code ELIFECYCLE
21 error errno 1
22 error cocomusic@2.0.7 build:linux: `node .electron-vue/build.js && electron-builder -l tar.xz deb AppImage pacman`
22 error Exit status 1
23 error Failed at the cocomusic@2.0.7 build:linux script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
