### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by yangjunfocus** [xtuJSer/CoCoMusic#20]
npm install 报错说 ` Package require os(!win32) not compatible with your platform(win32)` ，请问大神如何解决？

**Comment by rekols** [comment]
提示很明显呀，你的是不是32为系统。

**Comment by yangjunfocus** [comment]
完整的错误如下 `| [65/66] Installing dbus@^0.2.11platform unsupported mpris-service@1.1.3 › dbus@^0.2.11 Package require os(!win32) not compatible with your platform(win32)
× Install fail! UnSupportedPlatformError: Package require os(!win32) not compatible with your platform(win32)
UnSupportedPlatformError: Package require os(!win32) not compatible with your platform(win32)
    at _install (C:\Users\ZouYou\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\lib\install.js:197:19)
    at _install.next (<anonymous>)
    at onFulfilled (C:\Users\ZouYou\AppData\Roaming\npm\node_modules\cnpm\node_modules\co\index.js:65:19)
    at <anonymous>`

**Comment by fengT-T** [comment]
更新了依赖配置，可以使用了。
